### ISSUE TITLE
console error undefined function bold

### ISSUE THREAD

**Issue by ghost** [soncodi/gulp-cssretarget#1]
var gulp                   = require('gulp');
var uglify          = require('gulp-uglify'); 
var concat      = require('gulp-concat');
var minify_css      = require('gulp-minify-css');
var concat_css  = require('gulp-concat-css');
var autoprefixer    = require('gulp-autoprefixer');
var cssretarget     = require('gulp-cssretarget');

gulp.task('css', function(){
    gulp.src([
        'assets/css/file1.css',
        'assets/css/file2.css',
        'assets/css/plugins/file3.css', 
        'assets/css/plugins/file4.css',
        'assets/css/file5.css'
    ])
    .pipe(concat_css('style.css'))
    .pipe(cssretarget())
    .pipe(minify_css({
        keepSpecialComments:1,
        keepBreaks: false,
    }))
    .pipe(gulp.dest(''));
});

undefined function bold() { [native code] } => undefined undefined 
![err](https://cloud.githubusercontent.com/assets/3582546/6185193/df878806-b36b-11e4-8e57-9b09c728c5a3.PNG)

NOTE, the output file is correct, just thought I'd leave a note about that console error.

**Comment by soncodi** [comment]
One of the deps (gulp-util/chalk/colors) broke compat. I've fixed the code and published a new version on npm. Thanks for the report.

**Comment by ghost** [comment]
Great, thanks!
